name: CI Pipeline
on: push
jobs:
  name: code testing
  runs-on: ubuntu-latest
  steps:
  - name: code checkout
    uses: actions/checkout@v3

  - name: python setup
    uses: actions/setup-python@v2
    with:
      python-version: '3.10'

  - name: install dependencies
    run: |
      pip install -r requirements

  - name: run pipeline
    run: |
      dvc repro
